# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('docfile', models.FileField(upload_to='bills')),
                ('status', models.CharField(choices=[('Unseen', '\u041d\u0430 \u0440\u0430\u0441\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0438'), ('Approved', '\u0423\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043e'), ('Denide', '\u041e\u0442\u043a\u043b\u043e\u043d\u0435\u043d\u043e')], max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_begin', models.DateTimeField(verbose_name='date of begin')),
                ('date_end', models.DateTimeField(verbose_name='date of end')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='getbills.Application')),
            ],
        ),
    ]
