# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getbills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
