# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getbills', '0002_auto_20160726_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
